"""Every shipped country profile must load, honour the data contract, and produce a sane LCOE.

Guards the Ember-sourced country data (backend/data/country_profiles/*.json, generated by
backend/data/build_country_profiles.py) against a broken schema, a bad fuel mapping, or an
implausible value slipping in when the profiles are regenerated.
"""

from __future__ import annotations

import csv
import json
from collections import defaultdict
from pathlib import Path

import pytest

from backend.core.lcoe_engine import PROFILE_DIR, calculate_system_lcoe, load_country_profile

_COUNTRY_CODES = sorted(path.stem for path in PROFILE_DIR.glob("*.json"))
_BUCKETS = ["solar", "wind_onshore", "gas_ccgt", "coal", "nuclear", "other"]
_REFERENCE_MIX = {
    "solar": 0.15, "wind_onshore": 0.10, "gas_ccgt": 0.30,
    "coal": 0.25, "nuclear": 0.18, "other": 0.02,
}
# Physical CF bands mirrored from build_country_profiles.CF_BOUNDS (must stay in sync).
_CF_BOUNDS = {
    "solar": (0.07, 0.30), "wind_onshore": (0.10, 0.55), "gas_ccgt": (0.10, 0.90),
    "coal": (0.10, 0.90), "nuclear": (0.40, 0.95), "other": (0.10, 0.85),
}
_EMBER_CSV = Path(__file__).resolve().parents[1] / "data" / "ember" / "yearly_full_release_long_format.csv"
_FUEL_TO_BUCKET = {
    "Solar": "solar", "Wind": "wind_onshore", "Gas": "gas_ccgt", "Coal": "coal",
    "Nuclear": "nuclear", "Hydro": "other", "Bioenergy": "other", "Other Fossil": "other",
    "Other Renewables": "other",
}
# code → Ember ISO-3, from the build's provenance manifest (regenerated with the profiles).
_MANIFEST = Path(__file__).resolve().parents[1] / "data" / "country_profiles_manifest.json"
_ISO3 = {
    code: meta["iso3"]
    for code, meta in json.loads(_MANIFEST.read_text())["countries"].items()
}


def test_at_least_the_core_countries_ship() -> None:
    assert len(_COUNTRY_CODES) >= 160  # global roster: every Ember country with demand ≥ 1 TWh
    assert {"KR", "US", "CN", "DE", "GB", "IN"}.issubset(_COUNTRY_CODES)


@pytest.mark.parametrize("code", _COUNTRY_CODES)
def test_country_profile_produces_sane_lcoe(code: str) -> None:
    result = calculate_system_lcoe(country=code, shares=_REFERENCE_MIX, carbon_price=50.0)
    assert 30.0 <= result["system_lcoe"] <= 400.0  # finite and in a plausible $/MWh band
    assert result["emission_intensity"] >= 0.0


@pytest.mark.parametrize("code", _COUNTRY_CODES)
def test_country_data_contract(code: str) -> None:
    """Ember-sourced fields exist, are internally consistent, and physically bounded."""
    p = load_country_profile(code)
    assert p["annual_generation_twh"] > 0
    assert isinstance(p.get("data_year"), int) and 2015 <= p["data_year"] <= 2035

    caps = p["capacities_gw"]
    shares = p["shares"]
    for bucket in _BUCKETS:
        assert caps[bucket] >= 0.0, f"{code} {bucket} capacity negative"
        assert shares[bucket] >= 0.0, f"{code} {bucket} share negative"
        lo, hi = _CF_BOUNDS[bucket]
        cf = p["generators"][bucket]["cf_base"]
        assert lo <= cf <= hi, f"{code} {bucket} cf_base {cf} outside [{lo},{hi}]"
    assert abs(sum(shares.values()) - 1.0) <= 0.01, f"{code} shares sum {sum(shares.values())}"


def _latest_settled_year() -> int:
    """Latest year Ember covers for >=60% of the best-covered year (excludes provisional years)."""
    cov: dict[int, set[str]] = defaultdict(set)
    with _EMBER_CSV.open(newline="") as f:
        for row in csv.DictReader(f):
            if row["Category"] == "Electricity generation" and row["Subcategory"] == "Total" and row["Unit"] == "TWh":
                cov[int(row["Year"])].add(row["ISO 3 code"])
    counts = {y: len(s) for y, s in cov.items()}
    threshold = 0.6 * max(counts.values())
    return max(y for y, c in counts.items() if c >= threshold)


def _ember_country(iso3: str, year_cap: int) -> dict | None:
    """Independently re-derive demand / capacity / generation for a country from Ember."""
    demand: dict[int, float] = {}
    total: dict[int, float] = {}
    cap: dict[int, dict[str, float]] = defaultdict(lambda: defaultdict(float))
    gen: dict[int, dict[str, float]] = defaultdict(lambda: defaultdict(float))
    other_fossil: dict[int, float] = defaultdict(float)
    with _EMBER_CSV.open(newline="") as f:
        for row in csv.DictReader(f):
            if row["ISO 3 code"] != iso3:
                continue
            y = int(row["Year"])
            cat, sub, var, unit = row["Category"], row["Subcategory"], row["Variable"], row["Unit"]
            val = float(row["Value"] or 0.0)
            if cat == "Electricity demand" and var == "Demand" and unit == "TWh":
                demand[y] = val
            elif cat == "Electricity generation" and sub == "Total" and unit == "TWh":
                total[y] = val
            elif cat == "Capacity" and sub == "Fuel" and unit == "GW" and var in _FUEL_TO_BUCKET:
                cap[y][_FUEL_TO_BUCKET[var]] += val
            elif cat == "Electricity generation" and sub == "Fuel" and unit == "TWh" and var in _FUEL_TO_BUCKET:
                gen[y][_FUEL_TO_BUCKET[var]] += val
                if var == "Other Fossil":
                    other_fossil[y] += val
    years = sorted(y for y in total if y <= year_cap and y in demand and y in cap and sum(cap[y].values()) > 0)
    if not years:
        return None
    y = years[-1]
    return {"year": y, "total": total[y], "cap": cap[y], "gen": gen[y], "other_fossil": other_fossil[y]}


@pytest.mark.skipif(not _EMBER_CSV.exists(), reason="Ember source CSV not present (git-ignored)")
@pytest.mark.parametrize("code", _COUNTRY_CODES)
def test_profile_matches_ember_source(code: str) -> None:
    """The shipped profile must reproduce the Ember source it claims (independent re-derivation)."""
    ember = _ember_country(_ISO3[code], _latest_settled_year())
    assert ember is not None, f"{code}: no complete Ember year"
    p = load_country_profile(code)
    assert p["data_year"] == ember["year"], f"{code} year mismatch"
    assert p["annual_generation_twh"] == pytest.approx(round(ember["total"], 2), abs=0.02)
    for bucket in _BUCKETS:
        expected = round(ember["cap"].get(bucket, 0.0), 3)
        shipped = p["capacities_gw"][bucket]
        if bucket == "wind_onshore":
            # Ember lumps all wind; we split offshore out, so onshore + offshore = Ember wind.
            shipped += p["capacities_gw"].get("wind_offshore", 0.0)
        assert shipped == pytest.approx(expected, abs=0.01), (
            f"{code} {bucket} capacity mismatch vs Ember"
        )

    # The "other" bucket's emissions and import-fuel weighting must follow the bucket's real
    # fossil share (Ember "Other Fossil" ÷ bucket generation): EF = 0.70 * f, weight = f.
    other_gen = ember["gen"].get("other", 0.0)
    if other_gen >= 0.05:
        f = min(max(ember["other_fossil"] / other_gen, 0.0), 1.0)
        other_block = p["generators"]["other"]
        assert other_block["emission_factor_tco2_mwh"] == pytest.approx(0.70 * f, abs=1e-3), (
            f"{code} other-bucket EF does not match Ember fossil share {f:.3f}"
        )
        assert other_block["import_fuel_fraction"] == pytest.approx(f, abs=1e-3)
