"""Every shipped country profile must load, honour the data contract, and produce a sane LCOE.

Guards the Ember-sourced country data (backend/data/country_profiles/*.json, generated by
backend/data/build_country_profiles.py) against a broken schema, a bad fuel mapping, or an
implausible value slipping in when the profiles are regenerated.
"""

from __future__ import annotations

import csv
import json
from collections import defaultdict
from pathlib import Path

import pytest

from backend.core.lcoe_engine import PROFILE_DIR, calculate_system_lcoe, load_country_profile

_COUNTRY_CODES = sorted(path.stem for path in PROFILE_DIR.glob("*.json"))
_BUCKETS = ["solar", "wind_onshore", "gas_ccgt", "coal", "nuclear", "hydro", "other"]
_REFERENCE_MIX = {
    "solar": 0.15, "wind_onshore": 0.10, "gas_ccgt": 0.30,
    "coal": 0.25, "nuclear": 0.18, "other": 0.02,
}
# Physical CF bands mirrored from build_country_profiles.CF_BOUNDS (must stay in sync).
_CF_BOUNDS = {
    "solar": (0.07, 0.30), "wind_onshore": (0.10, 0.55), "gas_ccgt": (0.10, 0.90),
    "coal": (0.10, 0.90), "nuclear": (0.40, 0.95), "hydro": (0.10, 0.65), "other": (0.10, 0.85),
}
_EMBER_CSV = Path(__file__).resolve().parents[1] / "data" / "ember" / "yearly_full_release_long_format.csv"
_FUEL_TO_BUCKET = {
    "Solar": "solar", "Wind": "wind_onshore", "Gas": "gas_ccgt", "Coal": "coal",
    "Nuclear": "nuclear", "Hydro": "hydro", "Bioenergy": "other", "Other Fossil": "other",
    "Other Renewables": "other",
}
# code → Ember ISO-3, from the build's provenance manifest (regenerated with the profiles).
_MANIFEST = Path(__file__).resolve().parents[1] / "data" / "country_profiles_manifest.json"
_ISO3 = {
    code: meta["iso3"]
    for code, meta in json.loads(_MANIFEST.read_text())["countries"].items()
}


def test_at_least_the_core_countries_ship() -> None:
    assert len(_COUNTRY_CODES) >= 160  # global roster: every Ember country with demand ≥ 1 TWh
    assert {"KR", "US", "CN", "DE", "GB", "IN"}.issubset(_COUNTRY_CODES)


@pytest.mark.parametrize("code", _COUNTRY_CODES)
def test_country_profile_produces_sane_lcoe(code: str) -> None:
    result = calculate_system_lcoe(country=code, shares=_REFERENCE_MIX, carbon_price=50.0)
    assert 30.0 <= result["system_lcoe"] <= 400.0  # finite and in a plausible $/MWh band
    assert result["emission_intensity"] >= 0.0


@pytest.mark.parametrize("code", _COUNTRY_CODES)
def test_country_data_contract(code: str) -> None:
    """Ember-sourced fields exist, are internally consistent, and physically bounded."""
    p = load_country_profile(code)
    assert p["annual_generation_twh"] > 0
    assert isinstance(p.get("data_year"), int) and 2015 <= p["data_year"] <= 2035

    caps = p["capacities_gw"]
    shares = p["shares"]
    for bucket in _BUCKETS:
        assert caps[bucket] >= 0.0, f"{code} {bucket} capacity negative"
        assert shares[bucket] >= 0.0, f"{code} {bucket} share negative"
        lo, hi = _CF_BOUNDS[bucket]
        cf = p["generators"][bucket]["cf_base"]
        assert lo <= cf <= hi, f"{code} {bucket} cf_base {cf} outside [{lo},{hi}]"
    assert abs(sum(shares.values()) - 1.0) <= 0.01, f"{code} shares sum {sum(shares.values())}"


def _latest_settled_year() -> int:
    """Latest year Ember covers for >=60% of the best-covered year (excludes provisional years)."""
    cov: dict[int, set[str]] = defaultdict(set)
    with _EMBER_CSV.open(newline="") as f:
        for row in csv.DictReader(f):
            if row["Category"] == "Electricity generation" and row["Subcategory"] == "Total" and row["Unit"] == "TWh":
                cov[int(row["Year"])].add(row["ISO 3 code"])
    counts = {y: len(s) for y, s in cov.items()}
    threshold = 0.6 * max(counts.values())
    return max(y for y, c in counts.items() if c >= threshold)


def _ember_country(iso3: str, year_cap: int) -> dict | None:
    """Independently re-derive demand / capacity / generation for a country from Ember."""
    demand: dict[int, float] = {}
    total: dict[int, float] = {}
    cap: dict[int, dict[str, float]] = defaultdict(lambda: defaultdict(float))
    gen: dict[int, dict[str, float]] = defaultdict(lambda: defaultdict(float))
    other_fossil: dict[int, float] = defaultdict(float)
    with _EMBER_CSV.open(newline="") as f:
        for row in csv.DictReader(f):
            if row["ISO 3 code"] != iso3:
                continue
            y = int(row["Year"])
            cat, sub, var, unit = row["Category"], row["Subcategory"], row["Variable"], row["Unit"]
            val = float(row["Value"] or 0.0)
            if cat == "Electricity demand" and var == "Demand" and unit == "TWh":
                demand[y] = val
            elif cat == "Electricity generation" and sub == "Total" and unit == "TWh":
                total[y] = val
            elif cat == "Capacity" and sub == "Fuel" and unit == "GW" and var in _FUEL_TO_BUCKET:
                cap[y][_FUEL_TO_BUCKET[var]] += val
            elif cat == "Electricity generation" and sub == "Fuel" and unit == "TWh" and var in _FUEL_TO_BUCKET:
                gen[y][_FUEL_TO_BUCKET[var]] += val
                if var == "Other Fossil":
                    other_fossil[y] += val
    years = sorted(y for y in total if y <= year_cap and y in demand and y in cap and sum(cap[y].values()) > 0)
    if not years:
        return None
    y = years[-1]
    return {"year": y, "total": total[y], "cap": cap[y], "gen": gen[y], "other_fossil": other_fossil[y]}


@pytest.mark.skipif(not _EMBER_CSV.exists(), reason="Ember source CSV not present (git-ignored)")
@pytest.mark.parametrize("code", _COUNTRY_CODES)
def test_profile_matches_ember_source(code: str) -> None:
    """The shipped profile must reproduce the Ember source it claims (independent re-derivation)."""
    ember = _ember_country(_ISO3[code], _latest_settled_year())
    assert ember is not None, f"{code}: no complete Ember year"
    p = load_country_profile(code)
    assert p["data_year"] == ember["year"], f"{code} year mismatch"
    assert p["annual_generation_twh"] == pytest.approx(round(ember["total"], 2), abs=0.02)
    for bucket in _BUCKETS:
        expected = round(ember["cap"].get(bucket, 0.0), 3)
        shipped = p["capacities_gw"][bucket]
        if bucket == "wind_onshore":
            # Ember lumps all wind; we split offshore out, so onshore + offshore = Ember wind.
            shipped += p["capacities_gw"].get("wind_offshore", 0.0)
        assert shipped == pytest.approx(expected, abs=0.01), (
            f"{code} {bucket} capacity mismatch vs Ember"
        )

    # The "other" bucket's emissions must follow the bucket's real fossil share (Ember "Other
    # Fossil" ÷ bucket generation): EF = 0.70 * f. Its import weighting is that fossil share
    # times the oil-import fraction (UN Comtrade), so it can never exceed f.
    other_gen = ember["gen"].get("other", 0.0)
    if other_gen >= 0.05:
        f = min(max(ember["other_fossil"] / other_gen, 0.0), 1.0)
        other_block = p["generators"]["other"]
        assert other_block["emission_factor_tco2_mwh"] == pytest.approx(0.70 * f, abs=1e-3), (
            f"{code} other-bucket EF does not match Ember fossil share {f:.3f}"
        )
        assert other_block["fossil_fraction"] == pytest.approx(f, abs=1e-3)
        assert 0.0 <= other_block["import_fuel_fraction"] <= f + 1e-3


_DEPENDENCY_JSON = Path(__file__).resolve().parents[1] / "data" / "energy_dependency.json"


_FIRM = ("gas_ccgt", "coal", "nuclear", "other")
_UNCAPPED = ("solar", "wind_onshore", "wind_offshore", "hydro")


@pytest.mark.parametrize("cf,expected", [
    (0.72, 0.8), (0.40, 0.4), (0.401, 0.5), (0.05, 0.1), (0.0, 0.1), (0.90, 0.9), (0.999, 1.0), (1.0, 1.0),
])
def test_ceil_to_step(cf: float, expected: float) -> None:
    from backend.data.build_country_profiles import ceil_to_step
    assert ceil_to_step(cf) == pytest.approx(expected, abs=1e-9)


@pytest.mark.skipif(not _EMBER_CSV.exists(), reason="Ember source CSV not present (git-ignored)")
def test_other_fuel_scaling_is_idempotent() -> None:
    """The 'other' (oil/diesel) fuel price scales from a fixed base × fossil share, so rebuilding
    a profile never re-scales an already-scaled value (regression for the compounding-to-zero bug;
    the structural template is itself a built profile)."""
    from backend.data.build_country_profiles import (
        COUNTRIES, PROFILE_DIR, TEMPLATE_COUNTRY, _load_energy_dependency,
        build_profile, extract_country, latest_settled_year, load_ember,
    )

    rows = load_ember()
    template = json.loads((PROFILE_DIR / f"{TEMPLATE_COUNTRY}.json").read_text())
    dep = _load_energy_dependency()
    year_cap = latest_settled_year(rows)
    for code in ("SA", "KR", "IN"):  # SA all-oil (f=1) must land on the full base, not near zero
        iso3, name = COUNTRIES[code]
        data = extract_country(rows, iso3, year_cap)
        once = build_profile(code, iso3, name, template, data, dep)
        twice = build_profile(code, iso3, name, once, data, dep)  # feed the built profile back in
        f1 = once["generators"]["other"]["fuel_usd_mmbtu"]
        f2 = twice["generators"]["other"]["fuel_usd_mmbtu"]
        assert f1 == pytest.approx(f2, abs=1e-9), f"{code} other fuel not idempotent: {f1} vs {f2}"
        if code == "SA":  # fossil_fraction 1.0 → the full 5.0 base
            assert f1 == pytest.approx(5.0, abs=1e-4)


@pytest.mark.parametrize("code", _COUNTRY_CODES)
def test_firm_max_cf_default(code: str) -> None:
    """Firm generators carry a default availability ceiling = real CF rounded up to a 10% mark;
    renewables and hydro never carry one; a firm plant the country lacks carries none either."""
    import math

    p = load_country_profile(code)
    g = p["generators"]
    for gen in _UNCAPPED:
        assert "max_cf" not in g[gen], f"{code} {gen} must be uncapped (weather/water-limited)"
    for gen in _FIRM:
        block = g[gen]
        cap = p["capacities_gw"].get(gen, 0.0)
        if "max_cf" not in block:
            assert cap < 0.20, f"{code} {gen} has capacity {cap} but no default max_cf"
            continue
        mc = block["max_cf"]
        # a clean 10% mark, in (0, 1], and never below the real CF it ceilings
        assert 0.10 <= mc <= 1.0, f"{code} {gen} max_cf {mc} out of range"
        assert abs(mc / 0.10 - round(mc / 0.10)) < 1e-6, f"{code} {gen} max_cf {mc} not a 10% mark"
        assert mc >= float(block["cf_base"]) - 1e-9, f"{code} {gen} max_cf {mc} < cf_base {block['cf_base']}"
        assert mc == pytest.approx(
            min(1.0, max(0.10, math.ceil(round(float(block["cf_base"]), 4) / 0.10 - 1e-9) * 0.10)), abs=1e-9
        )


@pytest.mark.skipif(not _DEPENDENCY_JSON.exists(), reason="energy_dependency.json not built")
def test_import_fractions_match_real_fuel_trade() -> None:
    """import_fuel_fraction comes from UN Comtrade net trade: fuel exporters burn domestic fuel
    (fraction ~0), all-import grids burn imported fuel (fraction ~1), and every fraction is a
    valid share."""
    for code in _COUNTRY_CODES:
        p = load_country_profile(code)
        for gen in ("gas_ccgt", "coal", "other"):
            frac = p["generators"][gen].get("import_fuel_fraction", 1.0)
            assert 0.0 <= frac <= 1.0, f"{code} {gen} import_fuel_fraction {frac}"

    anchors = {
        ("AU", "coal"): (0.0, 0.05),   # top coal exporter — power coal is domestic
        ("US", "gas_ccgt"): (0.0, 0.05),  # net gas exporter
        ("JP", "coal"): (0.95, 1.0),   # imports essentially all coal
        ("KR", "gas_ccgt"): (0.95, 1.0),  # imports all gas (LNG)
    }
    for (code, gen), (lo, hi) in anchors.items():
        frac = load_country_profile(code)["generators"][gen]["import_fuel_fraction"]
        assert lo <= frac <= hi, f"{code} {gen} expected [{lo},{hi}], got {frac}"
